### ISSUE TITLE
Demo hangs

### ISSUE THREAD

**Issue by samuelli** [raulsntos/noto-emoji-iconset#2]
Demo forces render of entire icon set, resulting in a a lockup. https://beta.webcomponents.org/element/raulsntos/noto-emoji-iconset/v0.0.6/demo/demo/index.html

Need to batch update or use something like iron-list maybe?

**Comment by raulsntos** [comment]
The commit c3c69c68caea0b2a48ca837b5e9094610e5e6110 should fix this. I'm using `iron-list` now. Thanks for the feedback!
Can you confirm this is working now? 
https://beta.webcomponents.org/preview/raulsntos/noto-emoji-iconset/c3c69c68caea0b2a48ca837b5e9094610e5e6110

**Comment by raulsntos** [comment]
I'll leave this issue opened waiting for confirmation.

**Comment by samuelli** [comment]
@raulsntos Works :), once you tag a release it'll update!

**Comment by raulsntos** [comment]
Great, I'll close this now
